# Generated by Django 4.0.4 on 2022-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('5C', '5C'), ('6C', '6C'), ('6T', '6T'), ('7C', '7C'), ('8C', '8C'), ('9C', '9C'), ('10C', '10C'), ('Teachers', 'Teachers')], default='5C', max_length=50, verbose_name='Grade')),
                ('name', models.CharField(max_length=50, verbose_name='LFM Names')),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Entered', 'Entered'), ('Left', 'Left')], max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Main Table',
                'verbose_name_plural': 'Main Tables',
            },
        ),
    ]
